'use strict';
// wavelength-cartes.js — Spectres (paires de notions opposées), gauche → droite.
// Comme sur les cartes du jeu, chaque carte a deux faces : le médium choisit
// l'un des deux spectres qu'on lui propose.
module.exports = [
  ['Froid', 'Chaud'],
  ['Inutile', 'Utile'],
  ['Sous-coté', 'Surcoté'],
  ['Film nul', 'Film génial'],
  ['Pas cher', 'Hors de prix'],
  ['Inconnu', 'Célèbre'],
  ['Sûr', 'Dangereux'],
  ['Lent', 'Rapide'],
  ['Mou', 'Dur'],
  ['Triste', 'Joyeux'],
  ['Laid', 'Beau'],
  ['Sale', 'Propre'],
  ['Silencieux', 'Bruyant'],
  ['Simple', 'Compliqué'],
  ['Réel', 'Imaginaire'],
  ['Naturel', 'Artificiel'],
  ['Sérieux', 'Ridicule'],
  ['Prévisible', 'Surprenant'],
  ['Lâche', 'Courageux'],
  ['Léger', 'Lourd'],
  ['Facile à apprendre', 'Difficile à maîtriser'],
  ['Mauvais pour la santé', 'Bon pour la santé'],
  ['Ennuyeux', 'Passionnant'],
  ['Courant', 'Rare'],
  ['Campagne', 'Ville'],
  ['Introverti', 'Extraverti'],
  ['Éphémère', 'Éternel'],
  ['Logique', 'Émotionnel'],
  ['Fantasy', 'Science-fiction'],
  ['Amer', 'Sucré'],
  ['Pour enfants', 'Pour adultes'],
  ['Chaotique', 'Organisé'],
  ['Pessimiste', 'Optimiste'],
  ['Passé', 'Futur'],
  ['Superficiel', 'Profond'],
  ['Prudent', 'Risqué'],
  ['Petit plaisir', 'Grand bonheur'],
  ['Mauvaise habitude', 'Bonne habitude'],
  ['Mauvais cadeau', 'Super cadeau'],
  ['Méchant', 'Héros'],
  ['Tradition', 'Innovation'],
  ['Concret', 'Abstrait'],
  ['Improvisé', 'Planifié'],
  ['Pauvre', 'Riche'],
  ['Brut', 'Raffiné'],
  ['De niche', 'Grand public'],
  ['Amateur', 'Professionnel'],
  ['Petit', 'Énorme'],
  ['Fragile', 'Solide'],
  ['Passif', 'Actif'],
  ['Crédible', 'Invraisemblable'],
  ['Consensuel', 'Polémique'],
  ['Détendu', 'Stressant'],
  ['Démodé', 'Tendance'],
  ['Court', 'Interminable'],
  ['Original', 'Cliché'],
  ['Agréable', 'Pénible'],
  ['Anecdotique', 'Essentiel'],
  ['Timide', 'Audacieux'],
  ['Intuitif', 'Contre-intuitif'],
  ['Repas banal', 'Repas de fête'],
  ['Personnage secondaire', 'Personnage principal'],
  ['Nourriture de rue', 'Gastronomie'],
  ['Mauvais conseil', 'Bon conseil'],
  ['Tâche ménagère agréable', 'Tâche ménagère horrible'],
  ['Sport tranquille', 'Sport extrême'],
  ['Talent inutile', 'Talent utile'],
  ['Mauvais nom de chien', 'Bon nom de chien'],
  ['Métier facile', 'Métier difficile'],
  ['Ça sent mauvais', 'Ça sent bon'],
  ['Moche comme animal', 'Mignon comme animal'],
  ['Petite ville', 'Métropole'],
  ['Pire saison', 'Meilleure saison'],
  ['Vacances ratées', 'Vacances de rêve'],
  ['Jeu de société nul', 'Jeu de société génial'],
  ['Fruit', 'Légume'],
  ['Sandwich', 'Pas un sandwich'],
  ['Sport', 'Pas un sport'],
  ['Instrument facile', 'Instrument difficile'],
  ['Superpouvoir nul', 'Superpouvoir génial'],
  ['Mauvais film de Noël', 'Bon film de Noël'],
  ['Chanson triste', 'Chanson joyeuse'],
  ['Tenue décontractée', 'Tenue de soirée'],
  ['Boisson du matin', 'Boisson du soir'],
  ['Friandise saine', 'Friandise interdite'],
  ['Hygiénique', 'Dégoûtant'],
  ['Peu fiable', 'Fiable'],
  ['Très vieux', 'Tout neuf'],
  ['Discret', 'Voyant'],
  ['Arme de fortune nulle', 'Arme de fortune redoutable'],
  ['Mauvais endroit pour un rendez-vous', 'Endroit parfait pour un rendez-vous'],
  ['Compétence de survie inutile', 'Compétence de survie vitale'],
  ['Légal', 'Illégal'],
  ['Fait peur à personne', 'Terrifiant'],
  ['Facile à dessiner', 'Difficile à dessiner'],
  ['Mauvaise pizza', 'Bonne pizza'],
  ['Pas romantique', 'Très romantique'],
  ['Ne se partage pas', 'Se partage'],
  ['Moment gênant', 'Moment de gloire'],
  ['Mauvais animal de compagnie', 'Bon animal de compagnie'],
  ['Geek', 'Pas geek'],
  ['Philosophie de vie nulle', 'Philosophie de vie sage'],
  ['Chose qu’on jette', 'Chose qu’on garde'],
  ['Écologique', 'Polluant'],
  ['Juste', 'Injuste'],
  ['Petit mensonge', 'Gros mensonge'],
  ['Calme', 'Énervé'],
  ['Clair', 'Sombre'],
  ['Sec', 'Mouillé'],
  ['Épicé doux', 'Épicé brûlant'],
  ['Occasion ratée', 'Coup de génie'],
  ['Dessert léger', 'Dessert copieux'],
  ['Mauvais titre de livre', 'Bon titre de livre'],
  ['Hobby de grand-parent', 'Hobby d’ado'],
  ['Mauvaise idée de tatouage', 'Bonne idée de tatouage'],
  ['Peu connu', 'Iconique'],
  ['Ringard', 'Stylé'],
  ['Honnête', 'Menteur'],
  ['Sympathique', 'Antipathique'],
  ['Utile en cas de zombies', 'Inutile en cas de zombies'],
];
